# https://github.com/GuillaumeFalourd/poc-github-actions/actions/runs/944957106/workflow
name: Vaccine Reporter - BS4 Hourly Workflow

on:
  schedule:
  - cron: "0 * * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 

      - name: Install Python packages
        run: python -m pip install --upgrade pip requests bs4 pandas urllib3 lxml

      - name: Execute Python script #
        run: |
          python run_hourly.py
      - name: Commit and Push new file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "added hourly data"
          git push
