name: BS4 Workflow

on:
  schedule:
  - cron: "5 * * * *" # 
  timezone: "Asia/Tokyo"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests bs4 pandas urllib3 lxml

      - name: Execute Python script # Run the run.py to get the latest data
        run: |
          python run.py
      - name: Commit and Push new file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "added new data"
          git push
